import { TimelineEvent, PortfolioItem, CourseCategory } from './types';

export const timelineEvents: TimelineEvent[] = [
  { year: '2013', title: 'Established Brand Name', description: 'Infinity Studies & Technical Solutions', color: 'bg-teal-200' },
  { year: '2015', title: 'Expanded Operations', description: 'Within The Govt & Industrial sectors', color: 'bg-red-200' },
  { year: '2018', title: 'Expanded Portfolio', description: 'Expanded Accredited Professional Training Courses portfolio', color: 'bg-blue-200' },
  { year: '2020', title: 'Implemented E-learning', description: 'Blended Learning / E-learning solutions', color: 'bg-blue-300' },
  { year: '2021', title: 'Opened Second Branch', description: 'Branch in Dubai', color: 'bg-purple-300' },
  { year: '2022', title: 'New Business Unit', description: 'Creation of an Independent Health Care business unit & 100% Growth in loyal customers', color: 'bg-pink-300' },
  { year: '2023', title: 'Major Contract Awarded', description: 'Awarded HSE Matrix contract from ADNOC/ Extended a second Branch in Abu Dhabi', color: 'bg-green-300' },
  { year: '2024', title: 'Prime Locale Reallocation', description: 'Reallocation to a prime locale, thrived HSE training services', color: 'bg-green-200' },
];

export const portfolioItems: PortfolioItem[] = [
    { title: 'Accredited Training Courses', image: 'https://images.unsplash.com/photo-1543269865-cbf427effbad?q=80&w=2070&auto=format&fit=crop' },
    { title: 'Oil & Gas And Power Sector', image: 'https://images.unsplash.com/photo-1563821435336-71f0d06a4891?q=80&w=2071&auto=format&fit=crop' },
    { title: 'Leadership, Management Trainings & Consultancy', image: 'https://images.unsplash.com/photo-1552664730-d307ca884978?q=80&w=2070&auto=format&fit=crop' },
    { title: 'HSE Trainings & Consultancy', image: 'https://tse4.mm.bing.net/th/id/OIP.0BGy37CXWssHU90pPGm3TwHaE7?cb=ucfimg2ucfimg=1&rs=1&pid=ImgDetMain&o=7&rm=3' },
    { title: 'Information Technology (IT) & Telecommunication', image: 'https://images.unsplash.com/photo-1593720213428-28a5b9e94613?q=80&w=2070&auto=format&fit=crop' },
    { title: 'HealthCare Education & Consultancy', image: 'https://images.unsplash.com/photo-1576091160550-2173dba999ef?q=80&w=2070&auto=format&fit=crop' },
    { title: 'Hands-On Engineering Workshops', image: 'https://images.unsplash.com/photo-1518770660439-4636190af475?q=80&w=2070&auto=format&fit=crop' },
    { title: 'Corporate Team Building', image: 'https://images.unsplash.com/photo-1573496130407-57329f01f769?q=80&w=2069&auto=format&fit=crop' },
    { title: 'Custom E-Learning Platforms', image: 'https://images.unsplash.com/photo-1516321497487-e288fb19713f?q=80&w=2070&auto=format&fit=crop' },
];

export const partners = [
    { src: 'https://i.imgur.com/pOf3d9c.png', alt: 'Eutex' },
    { src: 'https://i.imgur.com/mYmI9pB.png', alt: 'Northwest' },
    { src: 'https://i.imgur.com/3YQ5m0G.png', alt: 'IDP' },
    { src: 'https://i.imgur.com/7g4kYJ2.png', alt: 'ICM' },
    { src: 'https://i.imgur.com/dK0M2Q3.png', alt: 'Skillmate' },
    { src: 'https://i.imgur.com/x0f6Q5Y.png', alt: 'Primegear' },
    { src: 'https://i.imgur.com/J3T9B6r.png', alt: 'EPCA' },
    { src: 'https://i.imgur.com/yF9b4J1.png', alt: 'Atlasco' },
];

export const accreditations = [
    { src: 'https://i.imgur.com/qL3gY7H.png', alt: 'ADNOC ICV' },
    { src: 'https://i.imgur.com/rG7b7oQ.png', alt: 'ISO 9001:2015' },
    { src: 'https://i.imgur.com/kS3D3fM.png', alt: 'ISO 14001' },
    { src: 'https://i.imgur.com/y1v2b1Q.png', alt: 'ISO 45001' },
    { src: 'https://i.imgur.com/Q2y1B5b.png', alt: 'AMCA' },
    { src: 'https://i.imgur.com/nL5mS3s.png', alt: 'American Caregiver Association' },
    { src: 'https://i.imgur.com/uJ8K4dC.png', alt: 'Highfield Qualifications' },
    { src: 'https://i.imgur.com/8Q9Z5bF.png', alt: 'American Safety & Health Institute' },
    { src: 'https://i.imgur.com/A6jQ4kG.png', alt: 'Exemplar Global' },
];

export const courseCategories: CourseCategory[] = [
    {
        name: "Accredited (Technical)",
        courses: [
            { code: 'TECH-001', programme: "ASME exam preparation & certification", duration: 'Varies' },
            { code: 'TECH-002', programme: "API exam preparation & certification", duration: 'Varies' },
            { code: 'TECH-003', programme: "NACE exam preparation & certification", duration: 'Varies' },
            { code: 'TECH-004', programme: "MOBIUS ISO Vibration Analysis CAT I, II & III", duration: 'Varies' },
            { code: 'TECH-005', programme: "MOBIUS Asset Reliability Practitioner CAT I,II & III", duration: 'Varies' },
            { code: 'TECH-006', programme: "[ARP-E] Reliability Engineer", duration: 'Varies' },
            { code: 'TECH-007', programme: "Machinery Lubrication Analysis level 1 & 2", duration: 'Varies' },
            { code: 'TECH-008', programme: "Non-Destructive Testing (NDT)", duration: 'Varies' },
            { code: 'TECH-009', programme: "CSWIP Visual Welding Inspector", duration: 'Varies' },
            { code: 'TECH-010', programme: "CSWIP 3.3U - ROV Inspector", duration: 'Varies' },
            { code: 'TECH-011', programme: "IOSH Managing Safely", duration: 'Varies' },
            { code: 'TECH-012', programme: "Certified Maintenance and Reliability Professional", duration: 'Varies' },
            { code: 'TECH-013', programme: "Certified Reliability Engineer", duration: 'Varies' },
            { code: 'TECH-014', programme: "CompEx 01-04; F; 12 & 14 training & exam", duration: 'Varies' },
            { code: 'TECH-015', programme: "Certified Electrical Safety Compliance Prof (CESCP)", duration: 'Varies' },
            { code: 'TECH-016', programme: "Electrical Isolation Certification", duration: 'Varies' },
            { code: 'TECH-017', programme: "Certified Fiber Optic Technician Levels 1 & 2", duration: 'Varies' },
            { code: 'TECH-018', programme: "Revit Architecture & Structure Essential Training", duration: 'Varies' },
            { code: 'TECH-019', programme: "Revit Structure Detailing and Drafting", duration: 'Varies' },
            { code: 'TECH-020', programme: "Revit Structure Families Training", duration: 'Varies' },
            { code: 'TECH-021', programme: "Revit MEP Essential Training - Mechanical", duration: 'Varies' },
            { code: 'TECH-022', programme: "Revit MEP Essential Training - HVAC", duration: 'Varies' },
            { code: 'TECH-023', programme: "Revit MEP Essential Training - Plumbing and Fire Fighting", duration: 'Varies' },
        ],
    },
    {
        name: "Technical & Industrial",
        courses: [
            { code: 'IND-001', programme: "Corrosion, Inspection, Metallurgy & Facility Integrity", duration: 'Varies' },
            { code: 'IND-002', programme: "Production, Drilling, Reservoir, Geology and Petroleum", duration: 'Varies' },
            { code: 'IND-003', programme: "Electrical, Power and Energy", duration: 'Varies' },
            { code: 'IND-004', programme: "Mechanical & Utilities", duration: 'Varies' },
            { code: 'IND-005', programme: "Civil Structures", duration: 'Varies' },
            { code: 'IND-006', programme: "Process Control, Instrumentation and Telecommunication", duration: 'Varies' },
            { code: 'IND-007', programme: "Carbon Credits & Storage", duration: 'Varies' },
            { code: 'IND-008', programme: "Enhanced Oil Recovery Fundamentals", duration: 'Varies' },
            { code: 'IND-009', programme: "Applied Reservoir Engineering", duration: 'Varies' },
            { code: 'IND-010', programme: "X-mas Tree & Wellhead Operations, Maintenance & Testing", duration: 'Varies' },
            { code: 'IND-011', programme: "Circuit Breakers & Switchgears Inspection & Troubleshooting", duration: 'Varies' },
            { code: 'IND-012', programme: "Electric Motor Testing, Operation, Protection & Troubleshooting", duration: 'Varies' },
            { code: 'IND-013', programme: "LV/MV/HV Circuit Breakers and Switchgears", duration: 'Varies' },
            { code: 'IND-014', programme: "Transformer Operation, Maintenance, Diagnosis & Testing", duration: 'Varies' },
            { code: 'IND-015', programme: "PLC & SCADA-Automation & Process Control", duration: 'Varies' },
            { code: 'IND-016', programme: "Power Plant Troubleshooting & Problem Solving", duration: 'Varies' },
            { code: 'IND-017', programme: "Centrifugal Compressor & Steam Turbine: Design & Operations", duration: 'Varies' },
            { code: 'IND-018', programme: "Control Valve & Actuators: Selection Testing, Troubleshooting & Mnt Gas Turbine Technology: Design, Inspection, Troubleshooting", duration: 'Varies' },
            { code: 'IND-019', programme: "Mechanical Seals: Designs, Application, Selection, Installation", duration: 'Varies' },
            { code: 'IND-020', programme: "API 580 Risk Based Inspection", duration: 'Varies' },
            { code: 'IND-021', programme: "Pipeline and Piping Inspection, Mnt, Repair & Integrity Assessment", duration: 'Varies' },
            { code: 'IND-022', programme: "Intelligent Pigging", duration: 'Varies' },
            { code: 'IND-023', programme: "Root Cause Failure Analysis", duration: 'Varies' },
        ],
    },
    {
        name: "Leadership & Management",
        courses: [
            { code: 'LM-001', programme: "Certified Customer Experience Practitioner (CCXP)", duration: 'Varies' },
            { code: 'LM-002', programme: "Certified Human Resources Professional", duration: 'Varies' },
            { code: 'LM-003', programme: "Certified Risk Management", duration: 'Varies' },
            { code: 'LM-004', programme: "Certified Digital Marketing Professional", duration: 'Varies' },
            { code: 'LM-005', programme: "Certified Supply Chain Management", duration: 'Varies' },
            { code: 'LM-006', programme: "Certified Training & Development Management", duration: 'Varies' },
            { code: 'LM-007', programme: "Certified Marketing Strategy", duration: 'Varies' },
            { code: 'LM-008', programme: "Business Continuity Management", duration: 'Varies' },
            { code: 'LM-009', programme: "CInP® – Certified Innovation Professional", duration: 'Varies' },
            { code: 'LM-010', programme: "CDTP® – Certified Design Thinking Professional", duration: 'Varies' },
            { code: 'LM-011', programme: "CInS® – Certified Innovation Strategist", duration: 'Varies' },
            { code: 'LM-012', programme: "Project Manament Professional® (PMP) add pmp popular", duration: 'Varies' },
            { code: 'LM-013', programme: "Professional Agile Leadership", duration: 'Varies' },
            { code: 'LM-014', programme: "Leadership Management Certification", duration: 'Varies' },
            { code: 'LM-015', programme: "Business Process Optimization and Modelling", duration: 'Varies' },
            { code: 'LM-016', programme: "Advanced Contract Management", duration: 'Varies' },
            { code: 'LM-017', programme: "Mastering Project Metrics, KPIs and Dashboards", duration: 'Varies' },
            { code: 'LM-018', programme: "Problem Solving & Decision Making Skills", duration: 'Varies' },
            { code: 'LM-019', programme: "Competency Frameworks and Assessment Tools", duration: 'Varies' },
            { code: 'LM-020', programme: "HR Strategy in Transforming Organization", duration: 'Varies' },
            { code: 'LM-021', programme: "Performance Management: Setting Objectives and Conducting Appraisals", duration: 'Varies' },
            { code: 'LM-022', programme: "Leading with Emotional Intelligence", duration: 'Varies' },
            { code: 'LM-023', programme: "The A – Z of Competency Frameworks", duration: 'Varies' },
            { code: 'LM-024', programme: "Balanced Score Card Professional", duration: 'Varies' },
            { code: 'LM-025', programme: "Managing Stress & Work-Life Balance", duration: 'Varies' },
            { code: 'LM-026', programme: "Happiness: Sustaining a Motivating Work Culture", duration: 'Varies' },
            { code: 'LM-027', programme: "PECB Certified ISO 9001 (Lead Auditor, Foundation, Introduction)", duration: 'Varies' },
            { code: 'LM-028', programme: "PECB Certified Six Sigma Green Belt", duration: 'Varies' },
        ],
    },
    {
        name: "Health, Safety & Environment",
        courses: [
            { code: 'HSE-POP-001', programme: "Radiation Protection Safety Officer Training", duration: 'Varies' },
            { code: 'HSE-POP-002', programme: "NEBOSH (IGC-International General Certificate)", duration: 'Varies' },
            { code: 'HSE-POP-003', programme: "OSHA: Occupational Safety and Health", duration: 'Varies' },
            { code: 'HSE-POP-004', programme: "NASP/IASP Advance Diploma in Occupational Health & Safety", duration: 'Varies' },
            { code: 'HSE-POP-005', programme: "HABC (TRAIN THE TRAINER – LEVEL 3)", duration: 'Varies' },
            { code: 'HSE-POP-006', programme: "Level 2 International Award in the Control of substances Hazardous to Health (COSHH)", duration: 'Varies' },
            { code: 'HSE-POP-007', programme: "Hazard Identification (Hazid) & Task Risk Assessment", duration: 'Varies' },
            { code: 'HSE-POP-008', programme: "Chemical and Biological Hazard", duration: 'Varies' },
            { code: 'HSE-POP-009', programme: "H2S Awareness training", duration: 'Varies' },
            { code: 'HSE-POP-010', programme: "Incident and Accident Investigation & Reporting", duration: 'Varies' },
            { code: 'HSE-POP-011', programme: "Confined Space Entry", duration: 'Varies' },
            { code: 'HSE-POP-012', programme: "Behavior-Based Safety & Safety Culture at Workplace", duration: 'Varies' },
            { code: 'HSE-POP-013', programme: "Emergency Preparedness & Response Management", duration: 'Varies' },
            { code: 'HSE-POP-014', programme: "Associate Safety Professional - ASP (BCSP)", duration: 'Varies' },
            { code: 'HSE-POP-015', programme: "Certified Fire Protection Specialist - CFPS (NFPA)", duration: 'Varies' },
            { code: 'HSE-POP-016', programme: "Certified Environmental Professional - CEP", duration: 'Varies' },
            { code: 'HSE-POP-017', programme: "Certified Safety Professional (CSP)", duration: 'Varies' },
            { code: 'HSE-POP-018', programme: "Canadian Registered Safety Professional (CRSP)", duration: 'Varies' },
            { code: 'HSE-POP-019', programme: "Certified Functional Safety Professional / Expert (CFSP/CFSE)", duration: 'Varies' },
            { code: 'HSE-POP-020', programme: "Certified Process Safety Professional (CCPSC)", duration: 'Varies' },
            { code: 'HSE-POP-021', programme: "Certified Industrial Hygienist (CIH)", duration: 'Varies' },
            { code: 'HSE-POP-022', programme: "ISO 31000 Risk Manager", duration: 'Varies' },
            { code: 'HSE-POP-023', programme: "ISO 18788 Security Operations Management", duration: 'Varies' },
            { code: 'HSE-POP-024', programme: "ISO 30414 Human Resource Management", duration: 'Varies' },
        ],
    },
    {
        name: "Information Technology",
        courses: [
            { code: 'IT-001', programme: "Practical Fundamentals of Telecommunications and Wireless", duration: 'Varies' },
            { code: 'IT-002', programme: "Best Practice in Industrial Data Communications", duration: 'Varies' },
            { code: 'IT-003', programme: "Cybersecurity for Automation, Control, and SCADA Systems", duration: 'Varies' },
            { code: 'IT-004', programme: "CCTV - Troubleshooting, Designing and Installing Digital & Analog Closed-Circuit TV Systems", duration: 'Varies' },
            { code: 'IT-005', programme: "Practical Troubleshooting, Design & Selection of Industrial Fiber Optic Systems", duration: 'Varies' },
            { code: 'IT-006', programme: "Fundamentals of Telecommunications and Wireless Communications", duration: 'Varies' },
            { code: 'IT-007', programme: "Practical Fundamentals of Voice over IP (VoIP) for Engineers and Technicians", duration: 'Varies' },
            { code: 'IT-008', programme: "PECB Certified ISO/IEC 27032 (Lead Cyber Security Manager, Cyber Security Foundation)", duration: 'Varies' },
            { code: 'IT-009', programme: "Telecommunication for Non Engineers", duration: 'Varies' },
            { code: 'IT-010', programme: "Cable Testing Technician", duration: 'Varies' },
            { code: 'IT-011', programme: "Fiber Optics Technician", duration: 'Varies' },
            { code: 'IT-012', programme: "Certified Information Systems Security Professional (CISSP)", duration: 'Varies' },
            { code: 'IT-013', programme: "PECB Certified ISO/IEC 27001 – ISMS (Lead Auditor, Lead Implementer, Foundation, Introduction)", duration: 'Varies' },
            { code: 'IT-014', programme: "PECB Certified ISO/IEC 27005 (Lead Risk Manager, Risk Manager, Foundation, Introduction)", duration: 'Varies' },
            { code: 'IT-015', programme: "PECB Certified ISO 9001 (Lead Auditor, Foundation, Introduction)", duration: 'Varies' },
            { code: 'IT-016', programme: "PECB Certified Six Sigma Green Belt", duration: 'Varies' },
            { code: 'IT-017', programme: "PECB Certified ISO/IEC 20000 – ITSMS (Lead Auditor, Lead Implementer, Foundation, Introduction)", duration: 'Varies' },
            { code: 'IT-018', programme: "CMMI Building Services Excellence (SVCE)", duration: 'Varies' },
        ]
    },
    {
        name: "Infinity HealthCare",
        courses: [
            { code: 'HC-001', programme: "First Aid - CPR (American Heart Association)", duration: 'Varies' },
            { code: 'HC-002', programme: "First Aid (Highfield UK)", duration: 'Varies' },
            { code: 'HC-003', programme: "Nursing Assistant", duration: 'Varies' },
            { code: 'HC-004', programme: "Professional Caregiving", duration: 'Varies' },
            { code: 'HC-005', programme: "Medical Coding", duration: 'Varies' },
            { code: 'HC-006', programme: "Sterile Processing Technician Certificate Training", duration: 'Varies' },
            { code: 'HC-007', programme: "Basic Life Support (BLS)", duration: 'Varies' },
            { code: 'HC-008', programme: "Infection Control - CME points", duration: 'Varies' },
            { code: 'HC-009', programme: "PALS (Patient Advice and Liaison Service)", duration: 'Varies' },
            { code: 'HC-010', programme: "ASHI Advanced First Aid", duration: 'Varies' },
            { code: 'HC-011', programme: "ASHI Advanced Cardiac Life Support (ACLS)", duration: 'Varies' },
            { code: 'HC-012', programme: "ASHI Basic First Aid", duration: 'Varies' },
            { code: 'HC-013', programme: "ASHI Basic Life Support (BLS)", duration: 'Varies' },
            { code: 'HC-014', programme: "ASHI Child and Babysitting Safety", duration: 'Varies' },
            { code: 'HC-015', programme: "ASHICPR, AED and First Aid COMBO", duration: 'Varies' },
            { code: 'HC-016', programme: "ASHI Emergency Medical Response", duration: 'Varies' },
            { code: 'HC-017', programme: "ASHI Emergency Oxygen", duration: 'Varies' },
            { code: 'HC-018', programme: "ASHI Instructor Development Course (IDC)", duration: 'Varies' },
            { code: 'HC-019', programme: "ASHI Pediatric CPR, AED, and First Aid", duration: 'Varies' },
        ],
    },
];